name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    runs-on: ubuntu-latest

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'adopt'
          cache: 'maven'

      - name: Build with Maven
        run: mvn clean install --quiet

      - name: Bump version and create a new tag
        id: bump_version
        run: |
          NEW_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout | awk -F. -v OFS=. '/[0-9]+[.][0-9]+[.][0-9]+/{print $1, $2, $3+1}')
          echo "new_version=$NEW_VERSION" >> $GITHUB_ENV
          git config --local user.name "github-actions"
          git config --local user.email "github-actions@github.com"
          mvn versions:set -DnewVersion=$NEW_VERSION
          mvn versions:commit
          git add .
          git commit -m "Bump version to ${{ env.new_version }}"
          git tag v${{ env.new_version }}

      - name: Push changes back to GitHub
        run: |
          git push origin HEAD:master --tags